/** Explorer copy is contributed to the existing Nexus translation namespace. */
export const inboxMessages = {
  "inbox.participants": "Participants",
  "inbox.relations": "Relations",
  "inbox.accessibleUses": "{count} accessible message uses",
  "inbox.previousMatch": "Previous match",
  "inbox.nextMatch": "Next match",
  "inbox.match": "Matches current filters",
  "inbox.transcriptCount": "{count} matching of {total} conversation messages",
  "inbox.clearMessages": "Clear message filters",
  "inbox.clearFinder": "Clear finder",

  "inbox.navigator": "Explore",
  "inbox.navigatorLens": "Explore by",
  "inbox.resultLens": "Show results as",
  "inbox.recipients": "Recipients",
  "inbox.handles": "Handles",
  "inbox.groups": "Group chats",
  "inbox.timeline": "Timeline",
  "inbox.attachments": "Attachments",
  "inbox.text": "Shared text",
  "inbox.messages": "Messages",
  "inbox.period": "Date range",
  "inbox.start": "Start date",
  "inbox.end": "End date",
  "inbox.timezone": "Timezone",
  "inbox.today": "Today",
  "inbox.7days": "Last 7 days",
  "inbox.30days": "Last 30 days",
  "inbox.directMail": "Direct & mail",
  "inbox.exactHandle": "Exact handle",
  "inbox.textRole": "Text role",
  "inbox.body": "Body",
  "inbox.signature": "Signature",
  "inbox.fading": "Fading relationships",
  "inbox.order": "Order",
  "inbox.latest": "Latest",
  "inbox.noCircles": "No circles match this search",
  "inbox.unitSummary": "{count} {unit} · {messages} matching messages",
  "inbox.unit.conversations": "conversations",
  "inbox.unit.timeline": "messages",
  "inbox.unit.attachments": "attachments",
  "inbox.unit.text": "shared texts",
  "inbox.connectionSummary": "{count} matching of {total} accessible {unit}",
  "inbox.accessibleCount": "{count} accessible {unit}",
  "inbox.matchingUses": "{count} matching uses",
  "inbox.sourceUse": "Source use",
  "inbox.fileUnavailable": "File unavailable",
  "inbox.circleScope": "Selected circle",
  "inbox.senderScope": "Selected identity",
  "inbox.axis.recency": "Recency",
  "inbox.axis.circle": "Circle",
  "inbox.axis.group": "Group chat",
  "inbox.axis.platform": "Platform",
  "inbox.axis.account": "Account",
  "inbox.axis.link": "Link state",
  "inbox.axis.organization": "Organisation",
  "inbox.axis.conversation": "Conversation",
  "inbox.axis.day": "Day",
  "inbox.axis.sender": "Sender",
  "inbox.relation.reply": "Reply",
  "inbox.relation.quote": "Quote",
  "inbox.relation.forward": "Forward",
  "inbox.relation.crosspost": "Crosspost",
  "inbox.relation.mention": "Mention",
  "inbox.title": "Inbox",
  "inbox.senders": "Senders",
  "inbox.everyone": "Everyone",
  "inbox.findSender": "Find a sender…",
  "inbox.search": "Search messages…",
  "inbox.searchRelated": "Search these uses…",
  "inbox.related": "Related",
  "inbox.filters": "Filters",
  "inbox.coverage": "Search coverage",
  "inbox.platform": "Platforms",
  "inbox.account": "Accounts",
  "inbox.kind": "Conversation kinds",
  "inbox.after": "From",
  "inbox.before": "Before",
  "inbox.attachment": "Attachments",
  "inbox.direction": "Direction",
  "inbox.quoted": "Include quotes & signatures",
  "inbox.starred": "Starred only",
  "inbox.sent": "Include my sent",
  "inbox.clear": "Clear filters",
  "inbox.clearCoverage": "Clear coverage",
  "inbox.all": "All",
  "inbox.circles": "Circles",
  "inbox.recent": "Latest activity",
  "inbox.oldest": "Oldest activity",
  "inbox.name": "Name",
  "inbox.count": "Message count",
  "inbox.first": "First contact",
  "inbox.confirmed": "Confirmed",
  "inbox.suggested": "Suggested",
  "inbox.unlinked": "Unlinked",
  "inbox.linkState": "Identity link",
  "inbox.noSenders": "No senders in this coverage",
  "inbox.noResults": "No matching results",
  "inbox.noResultsHint": "Adjust the filters or choose another sender.",
  "inbox.results": "Results",
  "inbox.conversation": "Conversation",
  "inbox.conversations": "Conversations",
  "inbox.summary":
    "{messages} matching messages · {conversations} conversations",
  "inbox.matched": "{matching} matching · {total} total",
  "inbox.read": "Read message",
  "inbox.message": "Message",
  "inbox.backResults": "Back to results",
  "inbox.backConversation": "Back to conversation",
  "inbox.openConversation": "Open conversation",
  "inbox.outside": "Outside current results",
  "inbox.details": "Message details",
  "inbox.exploreSender": "Explore sender",
  "inbox.alsoIn": "Also in {count} messages",
  "inbox.sameText": "Same text in {count} other messages",
  "inbox.noOtherUses": "No other readable uses",
  "inbox.relatedHint":
    "Choose a file or shared text to see its other message uses.",
  "inbox.relatedCount": "{count} readable message uses · all accounts",
  "inbox.source": "Original source",
  "inbox.returnSource": "Return to source",
  "inbox.closeRelated": "Close Related",
  "inbox.noRelated": "No matching uses",
  "inbox.sharedText": "Shared text",
  "inbox.file": "File",
  "inbox.copyLink": "Copy link",
  "inbox.copied": "Link copied",
  "inbox.star": "Star message",
  "inbox.unstar": "Unstar message",
  "inbox.preview": "File preview",
  "inbox.closePreview": "Back to message",
  "inbox.unavailable": "Message unavailable",
  "inbox.unknownSender": "Unknown sender",
  "inbox.standalone": "Standalone message",
  "inbox.loading": "Loading inbox…",
  "inbox.retry": "Retry",
  "inbox.error": "Inbox unavailable",
  "inbox.mail": "Mail",
  "inbox.direct": "Direct messages",
  "inbox.group": "Group conversations",
  "inbox.other": "Other",
  "inbox.any": "Any attachment",
  "inbox.image": "Images",
  "inbox.video": "Video",
  "inbox.audio": "Audio",
  "inbox.document": "Documents",
  "inbox.none": "No attachments",
  "inbox.inbound": "Inbound",
  "inbox.outbound": "Outbound",
  "inbox.status": "Status",
  "inbox.externalId": "Source ID",
  "inbox.received": "Received",
};
