"""Guard composed folder-addon dependency ownership."""

from __future__ import annotations

import tomllib
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest
from django.apps import AppConfig

from angee.compose import dependencies as dependencies_module
from angee.compose.dependencies import AddonDependencyGroup, AddonDependencyGroupResult
from angee.compose.runtime import Runtime


def _read_toml(path: Path) -> dict[str, Any]:
    """Return the TOML document at ``path`` using the standard-library parser."""

    with path.open("rb") as stream:
        return tomllib.load(stream)


def _app_config(path: Path, name: str, dependencies: tuple[str, ...] | None) -> AppConfig:
    """Return an AppConfig, optionally backed by an addon manifest."""

    path.mkdir(parents=True)
    module = ModuleType(name)
    module.__file__ = str(path / "apps.py")
    module.__path__ = [str(path)]  # type: ignore[attr-defined]
    if dependencies is not None:
        rendered_dependencies = ", ".join(f'"{dependency}"' for dependency in dependencies)
        (path / "addon.toml").write_text(
            f'[addon]\nname = "{name}"\ndependencies = [{rendered_dependencies}]\n',
            encoding="utf-8",
        )
    return AppConfig(name, module)


def test_composed_addon_dependencies_are_written_idempotently(tmp_path: Path) -> None:
    """Only composed folder-addon manifests project into the host group."""

    host = tmp_path / "host"
    host.mkdir()
    pyproject = host / "pyproject.toml"
    pyproject.write_text(
        '[project]\nname = "host"\nversion = "0.0.0"\n\n'
        '[dependency-groups]\ndev = ["pytest>=8"]\n',
        encoding="utf-8",
    )
    addon = _app_config(tmp_path / "fake-addon", "example.fake", ("zeta>=2", "alpha>=1", "alpha>=1"))
    plain_core = _app_config(tmp_path / "fake-core", "angee.base", None)
    projection = AddonDependencyGroup((addon, plain_core), project_dir=host)

    assert projection.write() is AddonDependencyGroupResult.WRITTEN
    first_stat = pyproject.stat()
    document = _read_toml(pyproject)
    assert document["dependency-groups"]["dev"] == ["pytest>=8"]
    assert document["dependency-groups"]["addons"] == ["alpha>=1", "zeta>=2"]
    assert pyproject.read_text(encoding="utf-8").count("GENERATED by angee build") == 1

    assert projection.write() is AddonDependencyGroupResult.UNCHANGED
    assert pyproject.stat().st_ino == first_stat.st_ino
    assert pyproject.stat().st_mtime_ns == first_stat.st_mtime_ns


def test_composed_addon_dependencies_are_idempotent_when_group_is_not_last(tmp_path: Path) -> None:
    """A table following the generated group does not cause byte drift."""

    host = tmp_path / "host"
    host.mkdir()
    pyproject = host / "pyproject.toml"
    pyproject.write_text(
        '[project]\nname = "host"\nversion = "0.0.0"\n\n'
        '[dependency-groups]\ndev = ["pytest>=8"]\n\n'
        '[tool.uv]\ndefault-groups = ["dev", "addons"]\n',
        encoding="utf-8",
    )
    addon = _app_config(tmp_path / "fake-addon", "example.fake_mid_group", ("alpha>=1",))
    projection = AddonDependencyGroup((addon,), project_dir=host)

    assert projection.write() is AddonDependencyGroupResult.WRITTEN
    first_write = pyproject.read_bytes()
    assert projection.write() is AddonDependencyGroupResult.UNCHANGED
    assert pyproject.read_bytes() == first_write


def test_composed_addon_dependencies_skip_a_bare_host(tmp_path: Path) -> None:
    """A unit-test or bare project with no pyproject is an explicit no-op."""

    addon = _app_config(tmp_path / "fake-addon", "example.fake_bare", ("alpha>=1",))
    host = tmp_path / "host"
    host.mkdir()

    projection = AddonDependencyGroup((addon,), project_dir=host)

    assert projection.write() is AddonDependencyGroupResult.SKIPPED_NO_PYPROJECT
    assert projection.check() is AddonDependencyGroupResult.SKIPPED_NO_PYPROJECT
    assert not (host / "pyproject.toml").exists()


def test_runtime_dependency_check_accepts_fresh_rejects_stale_and_skips_bare_host(tmp_path: Path) -> None:
    """Runtime check includes the compiled host dependency group when one exists."""

    host = tmp_path / "host"
    host.mkdir()
    pyproject = host / "pyproject.toml"
    pyproject.write_text('[project]\nname = "host"\nversion = "0.0.0"\n', encoding="utf-8")
    addon = _app_config(tmp_path / "fake-addon", "example.fake_check", ("alpha>=1",))
    runtime = Runtime((addon,), runtime_dir=tmp_path / "runtime", project_dir=host)

    assert runtime.build() is AddonDependencyGroupResult.WRITTEN
    assert runtime.build() is AddonDependencyGroupResult.UNCHANGED
    runtime.check()

    pyproject.write_text(pyproject.read_text(encoding="utf-8").replace("alpha>=1", "stale>=1"), encoding="utf-8")
    with pytest.raises(RuntimeError, match="host addon dependency group is stale"):
        runtime.check()

    pyproject.unlink()
    runtime.check()


def test_runtime_build_reports_a_missing_project_directory(tmp_path: Path) -> None:
    """Runtime delegates the no-project result instead of making the command infer it."""

    addon = _app_config(tmp_path / "fake-addon", "example.fake_no_project", ("alpha>=1",))
    runtime = Runtime((addon,), runtime_dir=tmp_path / "runtime", project_dir=None)

    assert runtime.build() is AddonDependencyGroupResult.SKIPPED_NO_PROJECT_DIR


def test_composed_addon_dependency_write_wraps_os_errors(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Atomic replacement failures reach the command as clean runtime errors."""

    host = tmp_path / "host"
    host.mkdir()
    (host / "pyproject.toml").write_text('[project]\nname = "host"\nversion = "0.0.0"\n', encoding="utf-8")
    addon = _app_config(tmp_path / "fake-addon", "example.fake_write_error", ("alpha>=1",))

    def fail_write(*_args: object, **_kwargs: object) -> None:
        raise OSError("read-only pyproject")

    monkeypatch.setattr(dependencies_module, "write_block", fail_write)

    with pytest.raises(RuntimeError, match="read-only pyproject"):
        AddonDependencyGroup((addon,), project_dir=host).write()
