import { createThemeCustomizationOptions, defineTheme, migrateThemeCustomization } from "@angee/ui/theme-runtime";

function migrate(value, fromVersion, defaults) {
  if (fromVersion !== 1) throw new TypeError(`Angee theme options version ${fromVersion} cannot be migrated.`);
  return migrateThemeCustomization(value, defaults);
}

export const themes = [defineTheme({
  contractVersion: 1,
  id: "angee.angee",
  labelKey: "angee.label",
  descriptionKey: "angee.description",
  revision: 3,
  tokens: {
    shared: {
      "--font-family-sans": "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
      "--r-2": "2px",
      "--r-4": "4px",
      "--r-6": "6px",
      "--r-8": "8px",
      "--r-10": "10px",
      "--r-12": "12px",
      "--control-h-sm": "26px",
      "--control-h-md": "32px",
      "--control-h-lg": "38px",
    },
    light: {
      "--surface-canvas": "#fafaf9",
      "--surface-sheet": "#ffffff",
      "--surface-sheet-2": "#f4f4f5",
      "--surface-rail": "#09090b",
      "--surface-rail-hi": "#27272a",
      "--surface-popover": "#ffffff",
      "--surface-inset": "#f4f4f5",
      "--text-primary": "#18181b",
      "--text-secondary": "#3f3f46",
      "--text-muted": "#71717a",
      "--text-subtle": "#a1a1aa",
      "--text-inverse": "#fafafa",
      "--text-on-rail": "#fafafa",
      "--text-on-rail-mut": "#a1a1aa",
      "--text-on-rail-hi": "#ffffff",
      "--text-on-brand": "#09090b",
      "--text-link": "#805f00",
      "--border-subtle": "#e4e4e7",
      "--border-default": "#d4d4d8",
      "--border-strong": "#a1a1aa",
      "--border-focus": "#e7b008",
      "--border-on-rail": "#27272a",
      "--brand": "#e7b008",
      "--brand-hover": "#ca9600",
      "--brand-active": "#a97800",
      "--brand-soft": "#fef3c7",
      "--brand-soft-text": "#725400",
      "--accent": "#6366f1",
      "--accent-soft": "#e0e7ff",
      "--accent-soft-text": "#4338ca",
      "--success-soft": "#dcfce7",
      "--success-text": "#166534",
      "--warning-soft": "#fef3c7",
      "--warning-text": "#854d0e",
      "--danger-soft": "#fee2e2",
      "--danger-text": "#b91c1c",
      "--info-soft": "#e0e7ff",
      "--info-text": "#4338ca",
      "--ring": "0 0 0 3px rgb(231 176 8 / 30%)",
      "--ring-danger": "0 0 0 3px rgb(220 38 38 / 30%)",
    },
    dark: {
      "--surface-canvas": "#09090b",
      "--surface-sheet": "#111113",
      "--surface-sheet-2": "#18181b",
      "--surface-rail": "#050506",
      "--surface-rail-hi": "#27272a",
      "--surface-popover": "#18181b",
      "--surface-inset": "#27272a",
      "--text-primary": "#fafafa",
      "--text-secondary": "#d4d4d8",
      "--text-muted": "#a1a1aa",
      "--text-subtle": "#71717a",
      "--text-inverse": "#18181b",
      "--text-on-rail": "#fafafa",
      "--text-on-rail-mut": "#a1a1aa",
      "--text-on-rail-hi": "#ffffff",
      "--text-on-brand": "#09090b",
      "--text-link": "#facc15",
      "--border-subtle": "#27272a",
      "--border-default": "#3f3f46",
      "--border-strong": "#52525b",
      "--border-focus": "#e7b008",
      "--border-on-rail": "#27272a",
      "--brand": "#e7b008",
      "--brand-hover": "#facc15",
      "--brand-active": "#fde047",
      "--brand-soft": "#33270a",
      "--brand-soft-text": "#facc15",
      "--accent": "#818cf8",
      "--accent-soft": "#252550",
      "--accent-soft-text": "#c7d2fe",
      "--success-soft": "#12351f",
      "--success-text": "#86efac",
      "--warning-soft": "#3b2b0a",
      "--warning-text": "#fde047",
      "--danger-soft": "#421718",
      "--danger-text": "#fca5a5",
      "--info-soft": "#22254f",
      "--info-text": "#c7d2fe",
      "--ring": "0 0 0 3px rgb(231 176 8 / 35%)",
      "--ring-danger": "0 0 0 3px rgb(248 113 113 / 35%)",
    },
  },
  options: createThemeCustomizationOptions({
    brand: "#e7b008",
    accent: "#6366f1",
    neutral: "#71717a",
    canvas: "#fafaf9",
    surface: "#ffffff",
    rail: "#09090b",
    success: "#22c55e",
    warning: "#eab308",
    danger: "#dc2626",
    info: "#4f46e5",
    font: "theme",
    radius: "theme",
    density: "theme",
    elevation: "theme",
    logo: "theme",
  }, { version: 2, migrate }),
})];
