"""Preserve thread group audiences while moving ThreadSpace.group to groups.

Reverse is intentionally not data-preserving because collapsing M2M audiences back
to one FK would be lossy.
"""

from __future__ import annotations

from itertools import islice
from typing import Any

from django.core.exceptions import ImproperlyConfigured
from django.db import migrations, models
from django.db.migrations.state import ProjectState

_BATCH_SIZE = 1_000
_GROUP_MODEL_LABEL = "spaces.group"


def applies(project_state: ProjectState) -> bool:
    """Return whether messaging.Thread still has the exact legacy single group FK."""

    thread = project_state.models.get(("messaging", "thread"))
    if thread is None:
        return False
    group = thread.fields.get("group")
    groups = thread.fields.get("groups")
    has_group = group is not None
    has_groups = groups is not None
    if has_group and not has_groups:
        if not _is_legacy_group_field(group):
            raise ImproperlyConfigured(
                "angee.spaces:thread_groups found an unexpected Thread.group field"
            )
        return True
    if has_groups and not has_group:
        if not _is_current_groups_field(groups):
            raise ImproperlyConfigured(
                "angee.spaces:thread_groups found an unexpected Thread.groups field"
            )
        return False
    if has_group and has_groups:
        raise ImproperlyConfigured(
            "angee.spaces:thread_groups found a partial ThreadSpace group transition: "
            "both group and groups are present"
        )
    return False


def copy_thread_group_to_groups(apps, schema_editor) -> None:
    """Copy each legacy Thread.group FK into the new Thread.groups M2M table."""

    thread_model = apps.get_model("messaging", "Thread")
    group_model = apps.get_model("spaces", "Group")
    through_model = thread_model.groups.through
    database = schema_editor.connection.alias
    thread_field = _through_field_for(through_model, thread_model)
    group_field = _through_field_for(through_model, group_model)
    rows = (
        thread_model._base_manager.using(database)
        .filter(group_id__isnull=False)
        .order_by("pk")
        .values_list("pk", "group_id")
    )
    through_rows = (
        through_model(
            **{
                thread_field.attname: thread_id,
                group_field.attname: group_id,
            }
        )
        for thread_id, group_id in rows.iterator(chunk_size=_BATCH_SIZE)
    )
    while batch := list(islice(through_rows, _BATCH_SIZE)):
        through_model._base_manager.using(database).bulk_create(
            batch,
            batch_size=_BATCH_SIZE,
            ignore_conflicts=True,
        )


def _is_legacy_group_field(field: models.Field) -> bool:
    """Return whether ``field`` matches ThreadSpace's retired single group FK."""

    return (
        isinstance(field, models.ForeignKey)
        and _remote_model_label(field) == _GROUP_MODEL_LABEL
        and field.null is True
        and field.blank is True
        and field.remote_field.on_delete is models.SET_NULL
        and field.remote_field.related_name == "threads"
    )


def _is_current_groups_field(field: models.Field) -> bool:
    """Return whether ``field`` matches ThreadSpace's current group audience M2M."""

    return (
        isinstance(field, models.ManyToManyField)
        and _remote_model_label(field) == _GROUP_MODEL_LABEL
        and field.blank is True
        and field.remote_field.related_name == "threads"
    )


def _remote_model_label(field: models.Field) -> str | None:
    """Return a relation field's remote model label without importing live models."""

    remote = getattr(getattr(field, "remote_field", None), "model", None)
    if isinstance(remote, str):
        return remote.lower()
    meta = getattr(remote, "_meta", None)
    label = getattr(meta, "label", None)
    return label.lower() if isinstance(label, str) else None


def _through_field_for(through_model: type[models.Model], target_model: type[models.Model]) -> Any:
    """Return the FK field on an autogenerated M2M through model for one side."""

    for field in through_model._meta.fields:
        remote = getattr(getattr(field, "remote_field", None), "model", None)
        if remote is target_model:
            return field
    raise ImproperlyConfigured(
        f"{through_model._meta.label} has no FK to {target_model._meta.label}"
    )


class Migration(migrations.Migration):
    """Move ThreadSpace's single group pointer to a losslessly backfilled audience M2M."""

    dependencies = [("spaces", "__latest__")]
    operations = [
        migrations.AddField(
            model_name="thread",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="threads",
                to="spaces.group",
            ),
        ),
        migrations.RunPython(copy_thread_group_to_groups, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="thread",
            name="group",
        ),
    ]
