"""Generate harness adapters from canonical reviewer Markdown and MCP JSON.

Run from the framework repository with its Python environment. ``--check``
compares without writing; ordinary invocation regenerates the adapters.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]


def reviewer_adapter(source: Path) -> str:
    """Project one reviewer's YAML metadata and Markdown body into Codex TOML."""
    text = source.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"Missing reviewer frontmatter: {source}")
    metadata, body = text[4:].split("\n---\n", 1)
    fields = yaml.safe_load(metadata)
    if fields["name"] != source.stem:
        raise ValueError(f"Reviewer name differs from filename: {source}")
    lines = [
        "# Generated by .agents/tools/sync-adapters.py; edit the sibling .md file.",
        f"name = {json.dumps(fields['name'], ensure_ascii=False)}",
        f"description = {json.dumps(fields['description'], ensure_ascii=False)}",
        'developer_instructions = """',
        *(json.dumps(line, ensure_ascii=False)[1:-1] for line in body.strip().splitlines()),
        '"""',
    ]
    return "\n".join(lines) + "\n"


def mcp_adapter(source: Path) -> str:
    """Project the repository's stdio MCP servers into the Codex config adapter."""
    servers = json.loads(source.read_text(encoding="utf-8"))["mcpServers"]
    lines = ["# Generated by .agents/tools/sync-adapters.py; edit .mcp.json."]
    for name, config in sorted(servers.items()):
        if set(config) != {"command", "args"}:
            raise ValueError(f"Unsupported MCP adapter fields for {name}: {sorted(config)}")
        lines.extend(
            [
                "",
                f"[mcp_servers.{json.dumps(name)}]",
                f"command = {json.dumps(config['command'], ensure_ascii=False)}",
                f"args = {json.dumps(config['args'], ensure_ascii=False)}",
            ]
        )
    return "\n".join(lines) + "\n"


def adapters(root: Path = ROOT) -> dict[Path, str]:
    """Return deterministic destinations and content for every supported adapter."""
    outputs = {
        source.with_suffix(".toml"): reviewer_adapter(source)
        for source in sorted((root / ".agents/agents").glob("*.md"))
    }
    outputs[root / ".codex/config.toml"] = mcp_adapter(root / ".mcp.json")
    return outputs


def main() -> int:
    """Check or regenerate committed adapters without starting any harness."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for destination, content in adapters().items():
        if destination.exists() and destination.read_text(encoding="utf-8") == content:
            continue
        stale.append(destination.relative_to(ROOT))
        if not args.check:
            destination.write_text(content, encoding="utf-8")
    if stale:
        print(("Stale" if args.check else "Updated") + " adapters: " + ", ".join(map(str, stale)))
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
