// The rendered binding's runtime contracts. The DAG owner of the app-runtime
// registry (`AppRuntime` + its `useWidget`/`useContainer`/`usePreviews`/`useT` lookups),
// the context factory (`makeContext`), and the contribution contracts the render
// surfaces consume (menus, slots, previews, widgets, forms). `@angee/app` mounts
// the provider and builds addon manifests against these contracts.

export { makeContext, type ContextBinding } from "./make-context";
export { createAngeeI18nInstance } from "./i18n";
export {
  usePreferenceSlice,
  type PreferenceSliceState,
} from "./user-preferences";
export {
  EMPTY_CONTAINERS,
  containerName,
  containersFromChildren,
  modelChain,
  useDrawers,
  resolveContainer,
  useContainer,
  type ComposedContainerChild,
  type ComposedContainers,
  type ContainerAlteration,
  type ContainerChild,
  type ContainerCondition,
  type ContainerEntry,
  type ContainerKinds,
  type ContainerRule,
  type ContainerScope,
  type ContainersDeclaration,
  type CoreContainer,
  type ResolveContainerOptions,
  type ResourceViewKindContent,
  type DockedDrawerContent,
} from "./containers";
export {
  applyDeveloperModeSearch,
  useDeveloperMode,
  useDeveloperModeSwitch,
  useRuntimeComposition,
} from "./developer-mode";
export {
  AppRuntimeProvider,
  useAppRuntime,
  useWidget,
  useDashboardRegistry,
  useFormOverride,
  useResourceRoute,
  useResourceRecordHref,
  useResourceRecordMatchFields,
  useResourceRecordHrefLookup,
  useRouteHref,
  useActiveRoute,
  useLoginPath,
  useRuntimeAuth,
  useRuntimeBrand,
  useRuntimeViewAs,
  useRuntimeLogoutAction,
  useRuntimeUserPreferences,
  readRuntimeRouteShortcuts,
  isPresent,
  sessionPermitted,
  usePreviews,
  useChatterRoutes,
  useT,
  useNamespaceT,
  type AppRuntime,
  type RuntimeAuthState,
  type RuntimeAuthUser,
  type RuntimeViewAs,
  type RuntimeI18n,
  type RuntimeLogoutAction,
  type ResourceRecordHrefLookup,
  type RuntimeResourceRoutes,
  type RuntimeUserPreferences,
  type RuntimeUserPreferencesPatch,
  type RuntimeUserPreferencesState,
  DEFAULT_LOGIN_PATH,
  HOME_PATH_PREFERENCE_KEY,
  ROUTE_SHORTCUTS_PREFERENCE_KEY,
  type RuntimeRouteShortcut,
} from "./runtime";
export {
  RECORD_NAVIGATION_SEARCH_KEY,
  RECORD_TAB_SEARCH_KEY,
  RECORD_SEARCH_KEYS,
  aliasRouteHref,
  createRouteHref,
  routeParameterName,
  routeSearchString,
  UnknownRouteError,
  type RouteHref,
  type RouteHrefParams,
  type RouteHrefSearch,
  type RouteHrefSearchValue,
  type RuntimeRouteDescriptor,
  type RecordMatch,
  recordMatchValues,
} from "./route-href";
export { type RuntimeFormRegistration } from "./contracts";
export type {
  AppVocabulary,
  RuntimeVocabulary,
  ChatterTabContent,
  ChatterRoute,
  ChatterView,
  ChatterViewContext,
  ComposedMenuItem,
  DrawerContribution,
  DrawerEdge,
  FormOverrideMap,
  MenuItem,
  PreviewContribution,
  HiddenMenuItem,
  RemovedMenuItem,
  RuntimeBrand,
  RuntimeComposition,
  RuntimeSelection,
  RuntimeSelectionField,
  WidgetMap,
} from "./contracts";
