# Generated by Django 6.0.6 on 2026-10-04 16:05

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import angee.base.fields


def applies(state):
    """Recreate the execution schema once the new decision owner is available."""
    decision = state.models.get(("decisions", "decision"))
    return (
        ("workflows", "workflowversion") in state.models
        and ("workflows", "workflowrun") not in state.models
        and decision is not None
        and "form_schema" not in decision.fields
    )


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "__latest__"),
        ("decisions", "__latest__"),
        ("iam", "__latest__"),
        ("workflows", "__latest__"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("error", angee.base.fields.DiagnosticTextField(blank=True, default="", max_length=8192)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input", models.JSONField(default=dict)),
                (
                    "origin",
                    angee.base.fields.StateField(
                        choices=[
                            ("manual", "Manual"),
                            ("workflow", "Workflow"),
                            ("reprocess", "Reprocess"),
                            ("trigger", "Trigger"),
                        ],
                        db_index=True,
                        editable=False,
                        max_length=9,
                    ),
                ),
                ("outcome", models.CharField(blank=True, default="", max_length=63)),
                ("output", models.JSONField(default=dict)),
                ("prune_after", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "prune_reason",
                    angee.base.fields.DiagnosticTextField(blank=True, default="", editable=False, max_length=255),
                ),
                (
                    "relation",
                    angee.base.fields.StateField(
                        blank=True,
                        choices=[("owned", "Owned"), ("continuation", "Continuation")],
                        db_index=True,
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "reprocess_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reprocesses",
                        to="workflows.workflowrun",
                    ),
                ),
                ("request_key", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("run_as", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                (
                    "status",
                    angee.base.fields.StateField(
                        choices=[
                            ("running", "Running"),
                            ("waiting", "Waiting"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=False,
                        default="running",
                        max_length=9,
                    ),
                ),
                ("stopped_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "subject_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("subject_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "trigger_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="started_run",
                        to="workflows.triggerevent",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="workflows.workflowversion"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "_rebac_base",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("origin", "manual"),
                                ("parent_step__isnull", True),
                                ("reprocess_of__isnull", True),
                                ("trigger_event__isnull", True),
                            ),
                            models.Q(
                                ("origin", "workflow"),
                                ("parent_step__isnull", False),
                                ("reprocess_of__isnull", True),
                                ("trigger_event__isnull", True),
                            ),
                            models.Q(
                                ("origin", "reprocess"),
                                ("parent_step__isnull", True),
                                ("reprocess_of__isnull", False),
                                ("trigger_event__isnull", True),
                            ),
                            models.Q(
                                ("origin", "trigger"),
                                ("parent_step__isnull", True),
                                ("reprocess_of__isnull", True),
                                ("trigger_event__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="workflows_run_origin_cause",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finished_at__isnull", False), ("status__in", ("succeeded", "failed", "canceled"))
                            ),
                            models.Q(("finished_at__isnull", True), ("status__in", ("running", "waiting"))),
                            _connector="OR",
                        ),
                        name="workflows_run_finished_terminal",
                    ),
                ],
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=["subject_content_type", "subject_object_id"], name="workflows_run_subject"),
                    models.Index(
                        condition=models.Q(("status__in", ("succeeded", "failed", "canceled"))),
                        fields=["finished_at"],
                        name="workflows_run_finished",
                    ),
                ],
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StepRun",
            fields=[
                ("attempt", models.PositiveIntegerField(default=0)),
                (
                    "awaited_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiters",
                        to="workflows.workflowrun",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requesting_steps",
                        to="decisions.decision",
                    ),
                ),
                ("dispatched_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ("dispatches", models.PositiveIntegerField(default=0)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_token", models.UUIDField(blank=True, editable=False, null=True)),
                ("input", models.JSONField(default=dict)),
                ("map_index", models.PositiveIntegerField(default=0)),
                (
                    "node_key",
                    models.CharField(
                        help_text="A declared node key, with room for a map item's .body suffix.", max_length=68
                    ),
                ),
                ("notes", models.JSONField(default=list)),
                ("outcome", models.CharField(blank=True, default="", max_length=63)),
                ("output", models.JSONField(default=dict)),
                ("page_index", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "rank",
                    models.PositiveIntegerField(
                        editable=False, help_text="Execution order assigned once by the graph planner."
                    ),
                ),
                ("retries", models.PositiveIntegerField(default=0)),
                (
                    "retry_acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Pending duplicate-effect acknowledgement, transferred to the next committed attempt."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_runs",
                        to="workflows.workflowrun",
                    ),
                ),
                ("state", models.JSONField(default=dict)),
                (
                    "status",
                    angee.base.fields.StateField(
                        choices=[
                            ("ready", "Ready"),
                            ("running", "Running"),
                            ("waiting", "Waiting"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=False,
                        default="ready",
                        max_length=9,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("wait_reason", angee.base.fields.DiagnosticTextField(blank=True, default="", max_length=8192)),
                (
                    "waiting_kind",
                    angee.base.fields.StateField(
                        blank=True,
                        choices=[
                            ("time", "Time"),
                            ("record", "Record"),
                            ("decision", "Decision"),
                            ("map", "Map"),
                            ("run", "Run"),
                            ("error", "Error"),
                        ],
                        db_index=False,
                        max_length=8,
                        null=True,
                    ),
                ),
                ("wake_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "_rebac_base",
                "constraints": [
                    models.UniqueConstraint(fields=("run", "node_key", "map_index"), name="workflows_step_node_unique"),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("deadline_at__isnull", False), ("status", "running")),
                            models.Q(models.Q(("status", "running"), _negated=True), ("deadline_at__isnull", True)),
                            _connector="OR",
                        ),
                        name="workflows_step_running_deadline",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "waiting"), ("waiting_kind__isnull", False)),
                            models.Q(models.Q(("status", "waiting"), _negated=True), ("waiting_kind__isnull", True)),
                            _connector="OR",
                        ),
                        name="workflows_step_waiting_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "waiting"),
                                ("wait_reason", ""),
                                ("waiting_kind", "time"),
                                ("wake_at__isnull", False),
                            ),
                            models.Q(("status", "waiting"), ("wait_reason", ""), ("waiting_kind", "record")),
                            models.Q(
                                ("decision__isnull", False),
                                ("status", "waiting"),
                                ("wait_reason", ""),
                                ("waiting_kind", "decision"),
                                ("wake_at__isnull", True),
                            ),
                            models.Q(
                                ("awaited_run__isnull", False),
                                ("status", "waiting"),
                                ("wait_reason", ""),
                                ("waiting_kind", "run"),
                                ("wake_at__isnull", True),
                            ),
                            models.Q(
                                ("status", "waiting"),
                                ("wait_reason", ""),
                                ("waiting_kind", "map"),
                                ("wake_at__isnull", True),
                            ),
                            models.Q(
                                ("status", "waiting"),
                                ("waiting_kind", "error"),
                                ("wake_at__isnull", True),
                                models.Q(("wait_reason", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("status", "waiting"), _negated=True),
                                ("wait_reason", ""),
                                ("wake_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="workflows_step_wait_columns",
                    ),
                ],
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "waiting")), fields=["wake_at"], name="workflows_step_wake"
                    ),
                    models.Index(
                        condition=models.Q(("status", "running")),
                        fields=["deadline_at"],
                        name="workflows_step_deadline",
                    ),
                    models.Index(
                        condition=models.Q(("status", "ready")),
                        fields=["dispatched_at"],
                        name="workflows_step_dispatch",
                    ),
                ],
                "ordering": ("rank", "map_index", "pk"),
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StepAttempt",
            fields=[
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("effect_started_at", models.DateTimeField(blank=True, null=True)),
                ("error", angee.base.fields.DiagnosticTextField(blank=True, default="", max_length=8192)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField()),
                ("page_index", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "result",
                    angee.base.fields.StateField(
                        blank=True,
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed out"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=False,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("stacktrace", angee.base.fields.DiagnosticTextField(blank=True, default="", max_length=65536)),
                ("started_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "step_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="workflows.steprun"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "_rebac_base",
                "constraints": [
                    models.UniqueConstraint(fields=("step_run", "number"), name="workflows_attempt_number_unique"),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("finished_at__isnull", True), ("result__isnull", True)),
                            models.Q(("finished_at__isnull", False), ("result__isnull", False)),
                            _connector="OR",
                        ),
                        name="workflows_attempt_finished_result",
                    ),
                ],
                "default_manager_name": "objects",
                "indexes": [],
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StepRecord",
            fields=[
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contenttypes.contenttype"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("created", "Created"),
                            ("changed", "Changed"),
                            ("deleted", "Deleted"),
                            ("called", "Called"),
                        ],
                        default="read",
                        max_length=7,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="records", to="workflows.workflowrun"
                    ),
                ),
                (
                    "step_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="workflows.steprun",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "_rebac_base",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "step_run", "content_type", "object_id", "operation"),
                        name="workflows_step_record_unique",
                    )
                ],
                "default_manager_name": "objects",
                "indexes": [models.Index(fields=["content_type", "object_id"], name="workflows_step_record_target")],
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StepWatch",
            fields=[
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contenttypes.contenttype"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("pending", models.BooleanField(default=False, editable=False)),
                (
                    "step_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="watches", to="workflows.steprun"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "_rebac_base",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("step_run", "content_type", "object_id"), name="workflows_watch_record_unique"
                    )
                ],
                "default_manager_name": "objects",
                "indexes": [models.Index(fields=["content_type", "object_id"], name="workflows_watch_record")],
                "verbose_name_plural": "step watches",
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="parent_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_runs",
                to="workflows.steprun",
            ),
        ),
    ]
