# Generated by Django 6.0.6 on 2026-10-04 11:20

import django.db.models.deletion
from django.db import migrations, models


def applies(state):
    """Contribute the asking step link after both owners have removed groups."""
    decision = state.models.get(("decisions", "decision"))
    step = state.models.get(("workflows", "steprun"))
    return decision is not None and step is not None and "form_schema" not in decision.fields and "step_run" not in decision.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '__latest__'),
        ('workflows', '__latest__'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='step_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='workflows.steprun'),
        ),
    ]
