# Generated by Django 6.0.6 on 2026-10-04 11:18

from django.db import migrations, models


def applies(state):
    """Apply the complete old schema once; new hosts start with the current models."""
    model = state.models.get(("workflows", "steprun"))
    if model is None:
        return False
    return "decision_group" in model.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '__latest__'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='steprun',
            name='workflows_step_wait_columns',
        ),
        migrations.AddConstraint(
            model_name='steprun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'waiting'), ('wait_reason', ''), ('waiting_kind', 'time'), ('wake_at__isnull', False)), models.Q(('status', 'waiting'), ('wait_reason', ''), ('waiting_kind', 'record')), models.Q(('status', 'waiting'), ('wait_reason', ''), ('waiting_kind', 'decision'), ('wake_at__isnull', True)), models.Q(('awaited_run__isnull', False), ('status', 'waiting'), ('wait_reason', ''), ('waiting_kind', 'run'), ('wake_at__isnull', True)), models.Q(('status', 'waiting'), ('wait_reason', ''), ('waiting_kind', 'map'), ('wake_at__isnull', True)), models.Q(('status', 'waiting'), ('waiting_kind', 'operator'), ('wake_at__isnull', True), models.Q(('wait_reason', ''), _negated=True)), models.Q(models.Q(('status', 'waiting'), _negated=True), ('wait_reason', ''), ('wake_at__isnull', True)), _connector='OR'), name='workflows_step_wait_columns'),
        ),
        migrations.RemoveField(
            model_name='steprun',
            name='decision_group',
        ),
    ]
