# Generated by Django 6.0.6 on 2026-10-04 16:05

from django.db import migrations


def applies(state):
    """Discard executions using a retired decision relationship."""
    step = state.models.get(("workflows", "steprun"))
    decision = state.models.get(("decisions", "decision"))
    # A pre-rebuild history (graph rows in workflows.Step) is retired whole by retire_pre_rebuild.
    pre_rebuild = ("workflows", "step") in state.models
    return (
        not pre_rebuild
        and step is not None
        and "decision" not in step.fields
        and (decision is None or "step_run" not in decision.fields)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "__latest__"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StepWatch",
        ),
        migrations.DeleteModel(
            name="StepArtifact",
        ),
        migrations.DeleteModel(
            name="StepAttempt",
        ),
        migrations.DeleteModel(
            name="WorkflowRunEvidence",
        ),
        migrations.RemoveField(
            model_name="workflowrun",
            name="parent_step",
        ),
        migrations.RemoveField(
            model_name="workflowrun",
            name="reprocess_of",
        ),
        migrations.DeleteModel(
            name="StepRun",
        ),
        migrations.DeleteModel(
            name="WorkflowRun",
        ),
    ]
