/**
 * Curated list of Google Fonts — top 500+ by popularity.
 *
 * Source: Google Fonts public catalogue (fonts.google.com), sorted by
 * number of weekly views. Updated periodically — add new fonts at the end.
 *
 * Each entry: [familyName, category]
 *   category: "sans-serif" | "serif" | "monospace" | "display" | "handwriting"
 *
 * No API key required. Fonts are loaded on-demand via fonts.googleapis.com/css2.
 */

export type GoogleFontCategory =
  | "sans-serif"
  | "serif"
  | "monospace"
  | "display"
  | "handwriting";

export interface GoogleFont {
  family: string;
  category: GoogleFontCategory;
}

export const GOOGLE_FONTS: readonly GoogleFont[] = [
  // ── Top 50 — most used worldwide ──────────────────────────────────────────
  { family: "Roboto",                category: "sans-serif" },
  { family: "Open Sans",             category: "sans-serif" },
  { family: "Noto Sans",             category: "sans-serif" },
  { family: "Lato",                  category: "sans-serif" },
  { family: "Montserrat",            category: "sans-serif" },
  { family: "Roboto Condensed",      category: "sans-serif" },
  { family: "Source Sans 3",         category: "sans-serif" },
  { family: "Oswald",                category: "sans-serif" },
  { family: "Raleway",               category: "sans-serif" },
  { family: "Nunito",                category: "sans-serif" },
  { family: "Nunito Sans",           category: "sans-serif" },
  { family: "Ubuntu",                category: "sans-serif" },
  { family: "Inter",                 category: "sans-serif" },
  { family: "Poppins",               category: "sans-serif" },
  { family: "Merriweather",          category: "serif" },
  { family: "Playfair Display",      category: "serif" },
  { family: "Lora",                  category: "serif" },
  { family: "PT Sans",               category: "sans-serif" },
  { family: "Roboto Slab",           category: "serif" },
  { family: "Noto Serif",            category: "serif" },
  { family: "PT Serif",              category: "serif" },
  { family: "Libre Baskerville",     category: "serif" },
  { family: "Libre Franklin",        category: "sans-serif" },
  { family: "Rubik",                 category: "sans-serif" },
  { family: "Work Sans",             category: "sans-serif" },
  { family: "Fira Sans",             category: "sans-serif" },
  { family: "Mukta",                 category: "sans-serif" },
  { family: "Mulish",                category: "sans-serif" },
  { family: "Titillium Web",         category: "sans-serif" },
  { family: "Barlow",                category: "sans-serif" },
  { family: "Nanum Gothic",          category: "sans-serif" },
  { family: "Josefin Sans",          category: "sans-serif" },
  { family: "Quicksand",             category: "sans-serif" },
  { family: "DM Sans",               category: "sans-serif" },
  { family: "Hind",                  category: "sans-serif" },
  { family: "Cabin",                 category: "sans-serif" },
  { family: "Arimo",                 category: "sans-serif" },
  { family: "Kanit",                 category: "sans-serif" },
  { family: "Oxygen",                category: "sans-serif" },
  { family: "Karla",                 category: "sans-serif" },
  { family: "Inconsolata",           category: "monospace" },
  { family: "Source Code Pro",       category: "monospace" },
  { family: "Manrope",               category: "sans-serif" },
  { family: "Space Grotesk",         category: "sans-serif" },
  { family: "Noto Sans JP",          category: "sans-serif" },
  { family: "Noto Sans KR",          category: "sans-serif" },
  { family: "Noto Sans SC",          category: "sans-serif" },
  { family: "Dancing Script",        category: "handwriting" },
  { family: "Pacifico",              category: "display" },
  { family: "Lobster",               category: "display" },

  // ── Modern / trending ─────────────────────────────────────────────────────
  { family: "Outfit",                category: "sans-serif" },
  { family: "Plus Jakarta Sans",     category: "sans-serif" },
  { family: "Figtree",               category: "sans-serif" },
  { family: "Sora",                  category: "sans-serif" },
  { family: "Geist",                 category: "sans-serif" },
  { family: "Lexend",                category: "sans-serif" },
  { family: "Lexend Deca",           category: "sans-serif" },
  { family: "Be Vietnam Pro",        category: "sans-serif" },
  { family: "Urbanist",              category: "sans-serif" },
  { family: "Jost",                  category: "sans-serif" },
  { family: "Albert Sans",           category: "sans-serif" },
  { family: "Bricolage Grotesque",   category: "sans-serif" },
  { family: "Onest",                 category: "sans-serif" },
  { family: "Chivo",                 category: "sans-serif" },
  { family: "Epilogue",              category: "sans-serif" },
  { family: "Hanken Grotesk",        category: "sans-serif" },
  { family: "Schibsted Grotesk",     category: "sans-serif" },
  { family: "Familjen Grotesk",      category: "sans-serif" },
  { family: "Instrument Sans",       category: "sans-serif" },
  { family: "Mona Sans",             category: "sans-serif" },

  // ── IBM / Tech fonts ──────────────────────────────────────────────────────
  { family: "IBM Plex Sans",         category: "sans-serif" },
  { family: "IBM Plex Serif",        category: "serif" },
  { family: "IBM Plex Mono",         category: "monospace" },
  { family: "IBM Plex Sans Condensed", category: "sans-serif" },

  // ── DM family ─────────────────────────────────────────────────────────────
  { family: "DM Serif Display",      category: "serif" },
  { family: "DM Serif Text",         category: "serif" },
  { family: "DM Mono",               category: "monospace" },

  // ── Condensed / wide ─────────────────────────────────────────────────────
  { family: "Barlow Condensed",      category: "sans-serif" },
  { family: "Barlow Semi Condensed", category: "sans-serif" },
  { family: "Exo 2",                 category: "sans-serif" },
  { family: "Exo",                   category: "sans-serif" },
  { family: "Saira",                 category: "sans-serif" },
  { family: "Saira Condensed",       category: "sans-serif" },

  // ── Humanist sans ─────────────────────────────────────────────────────────
  { family: "Overpass",              category: "sans-serif" },
  { family: "Asap",                  category: "sans-serif" },
  { family: "Dosis",                 category: "sans-serif" },
  { family: "Varela Round",          category: "sans-serif" },
  { family: "Maven Pro",             category: "sans-serif" },
  { family: "Red Hat Display",       category: "sans-serif" },
  { family: "Red Hat Text",          category: "sans-serif" },
  { family: "Red Hat Mono",          category: "monospace" },
  { family: "Hind Siliguri",         category: "sans-serif" },
  { family: "Hind Madurai",          category: "sans-serif" },
  { family: "Hind Guntur",           category: "sans-serif" },
  { family: "Hind Vadodara",         category: "sans-serif" },
  { family: "Arvo",                  category: "serif" },
  { family: "Muli",                  category: "sans-serif" },
  { family: "Catamaran",             category: "sans-serif" },
  { family: "Assistant",             category: "sans-serif" },
  { family: "Tajawal",               category: "sans-serif" },
  { family: "Almarai",               category: "sans-serif" },
  { family: "Cairo",                 category: "sans-serif" },
  { family: "El Messiri",            category: "sans-serif" },

  // ── Geometric sans ────────────────────────────────────────────────────────
  { family: "Comfortaa",             category: "display" },
  { family: "Righteous",             category: "display" },
  { family: "Fredoka",               category: "sans-serif" },
  { family: "Fredoka One",           category: "display" },
  { family: "Nunito",                category: "sans-serif" },
  { family: "Rounded Mplus 1c",      category: "sans-serif" },
  { family: "M PLUS Rounded 1c",     category: "sans-serif" },
  { family: "M PLUS 1p",             category: "sans-serif" },
  { family: "Kumbh Sans",            category: "sans-serif" },

  // ── Serif — classic ───────────────────────────────────────────────────────
  { family: "Crimson Text",          category: "serif" },
  { family: "EB Garamond",           category: "serif" },
  { family: "Cormorant Garamond",    category: "serif" },
  { family: "Cormorant",             category: "serif" },
  { family: "Cormorant Infant",      category: "serif" },
  { family: "Cormorant SC",          category: "serif" },
  { family: "Cormorant Upright",     category: "serif" },
  { family: "Vollkorn",              category: "serif" },
  { family: "Source Serif 4",        category: "serif" },
  { family: "Bitter",                category: "serif" },
  { family: "Alegreya",              category: "serif" },
  { family: "Alegreya Sans",         category: "sans-serif" },
  { family: "Spectral",              category: "serif" },
  { family: "Frank Ruhl Libre",      category: "serif" },
  { family: "Yeseva One",            category: "display" },
  { family: "Tinos",                 category: "serif" },
  { family: "Noto Serif Display",    category: "serif" },
  { family: "Slabo 27px",            category: "serif" },
  { family: "Cardo",                 category: "serif" },
  { family: "Neuton",                category: "serif" },
  { family: "Domine",                category: "serif" },
  { family: "Gentium Book Plus",     category: "serif" },

  // ── Display / Decorative ──────────────────────────────────────────────────
  { family: "Abril Fatface",         category: "display" },
  { family: "Anton",                 category: "sans-serif" },
  { family: "Bebas Neue",            category: "display" },
  { family: "Big Shoulders Display", category: "display" },
  { family: "Teko",                  category: "sans-serif" },
  { family: "Passion One",           category: "display" },
  { family: "Alfa Slab One",         category: "display" },
  { family: "Changa One",            category: "display" },
  { family: "Squada One",            category: "display" },
  { family: "Lilita One",            category: "display" },
  { family: "Fjalla One",            category: "sans-serif" },
  { family: "Bangers",               category: "display" },
  { family: "Permanent Marker",      category: "handwriting" },
  { family: "Black Han Sans",        category: "sans-serif" },
  { family: "Secular One",           category: "sans-serif" },
  { family: "Archivo Black",         category: "sans-serif" },
  { family: "Arya",                  category: "sans-serif" },
  { family: "Baloo 2",               category: "display" },
  { family: "Boogaloo",              category: "display" },
  { family: "Bubblegum Sans",        category: "display" },
  { family: "Chewy",                 category: "display" },
  { family: "Fugaz One",             category: "display" },
  { family: "Russo One",             category: "sans-serif" },
  { family: "Titan One",             category: "display" },
  { family: "Ultra",                 category: "serif" },
  { family: "Gravitas One",          category: "display" },
  { family: "Monoton",               category: "display" },
  { family: "Paytone One",           category: "sans-serif" },
  { family: "Courgette",             category: "handwriting" },
  { family: "Clicker Script",        category: "handwriting" },

  // ── Handwriting / Script ──────────────────────────────────────────────────
  { family: "Great Vibes",           category: "handwriting" },
  { family: "Satisfy",               category: "handwriting" },
  { family: "Pacifico",              category: "display" },
  { family: "Sacramento",            category: "handwriting" },
  { family: "Tangerine",             category: "handwriting" },
  { family: "Allura",                category: "handwriting" },
  { family: "Caveat",                category: "handwriting" },
  { family: "Cookie",                category: "handwriting" },
  { family: "Crafty Girls",          category: "handwriting" },
  { family: "Homemade Apple",        category: "handwriting" },
  { family: "Indie Flower",          category: "handwriting" },
  { family: "Kaushan Script",        category: "handwriting" },
  { family: "Merienda",              category: "handwriting" },
  { family: "Pinyon Script",         category: "handwriting" },
  { family: "Playball",              category: "display" },
  { family: "Rouge Script",          category: "handwriting" },
  { family: "Yellowtail",            category: "handwriting" },
  { family: "Zeyada",                category: "handwriting" },
  { family: "Amatic SC",             category: "handwriting" },
  { family: "Bad Script",            category: "handwriting" },
  { family: "Charm",                 category: "handwriting" },

  // ── Monospace / Code ──────────────────────────────────────────────────────
  { family: "JetBrains Mono",        category: "monospace" },
  { family: "Roboto Mono",           category: "monospace" },
  { family: "Fira Code",             category: "monospace" },
  { family: "Fira Mono",             category: "monospace" },
  { family: "Space Mono",            category: "monospace" },
  { family: "Courier Prime",         category: "monospace" },
  { family: "Cousine",               category: "monospace" },
  { family: "Anonymous Pro",         category: "monospace" },
  { family: "Share Tech Mono",       category: "monospace" },
  { family: "Cutive Mono",           category: "monospace" },
  { family: "Nova Mono",             category: "monospace" },
  { family: "Overpass Mono",         category: "monospace" },
  { family: "PT Mono",               category: "monospace" },
  { family: "Ubuntu Mono",           category: "monospace" },
  { family: "Nanum Gothic Coding",   category: "monospace" },
  { family: "B612 Mono",             category: "monospace" },
  { family: "Azeret Mono",           category: "monospace" },

  // ── Slab Serif ────────────────────────────────────────────────────────────
  { family: "Rockwell",              category: "serif" },
  { family: "Zilla Slab",            category: "serif" },
  { family: "Crete Round",           category: "serif" },
  { family: "Yatra One",             category: "display" },
  { family: "Chonburi",              category: "display" },
  { family: "Glegoo",                category: "serif" },
  { family: "Josefin Slab",          category: "serif" },
  { family: "Podkova",               category: "serif" },
  { family: "Rokkitt",               category: "serif" },
  { family: "Aleo",                  category: "serif" },

  // ── Variable / modern ─────────────────────────────────────────────────────
  { family: "Recursive",             category: "sans-serif" },
  { family: "Cabinet Grotesk",       category: "sans-serif" },
  { family: "Clash Display",         category: "sans-serif" },
  { family: "Clash Grotesk",         category: "sans-serif" },
  { family: "General Sans",          category: "sans-serif" },
  { family: "Supreme",               category: "sans-serif" },
  { family: "Satoshi",               category: "sans-serif" },
  { family: "Switzer",               category: "sans-serif" },
  { family: "Nippo",                 category: "sans-serif" },
  { family: "Zodiak",                category: "serif" },
  { family: "Boska",                 category: "serif" },
  { family: "Spline Sans",           category: "sans-serif" },
  { family: "Spline Sans Mono",      category: "monospace" },

  // ── More popular picks ────────────────────────────────────────────────────
  { family: "Alata",                 category: "sans-serif" },
  { family: "Alike",                 category: "serif" },
  { family: "Allerta",               category: "sans-serif" },
  { family: "Allerta Stencil",       category: "sans-serif" },
  { family: "Amaranth",              category: "sans-serif" },
  { family: "Andada Pro",            category: "serif" },
  { family: "Antic",                 category: "sans-serif" },
  { family: "Antic Didone",          category: "serif" },
  { family: "Antic Slab",            category: "serif" },
  { family: "Antonio",               category: "sans-serif" },
  { family: "Armata",                category: "sans-serif" },
  { family: "Asap Condensed",        category: "sans-serif" },
  { family: "Aver",                  category: "sans-serif" },
  { family: "Belleza",               category: "sans-serif" },
  { family: "BenchNine",             category: "sans-serif" },
  { family: "Bentham",               category: "serif" },
  { family: "Besley",                category: "serif" },
  { family: "Boogaloo",              category: "display" },
  { family: "Cabin Condensed",       category: "sans-serif" },
  { family: "Cambo",                 category: "serif" },
  { family: "Cantarell",             category: "sans-serif" },
  { family: "Capriola",              category: "sans-serif" },
  { family: "Carme",                 category: "sans-serif" },
  { family: "Cedarville Cursive",    category: "handwriting" },
  { family: "Coda",                  category: "display" },
  { family: "Convergence",           category: "sans-serif" },
  { family: "Copse",                 category: "serif" },
  { family: "Cuprum",                category: "sans-serif" },
  { family: "Darker Grotesque",      category: "sans-serif" },
  { family: "David Libre",           category: "serif" },
  { family: "Didact Gothic",         category: "sans-serif" },
  { family: "Encode Sans",           category: "sans-serif" },
  { family: "Encode Sans Condensed", category: "sans-serif" },
  { family: "Encode Sans Expanded",  category: "sans-serif" },
  { family: "Enriqueta",             category: "serif" },
  { family: "Fauna One",             category: "serif" },
  { family: "Fenix",                 category: "serif" },
  { family: "Francois One",          category: "sans-serif" },
  { family: "Gantari",               category: "sans-serif" },
  { family: "Gelasio",               category: "serif" },
  { family: "Gilda Display",         category: "serif" },
  { family: "Gudea",                 category: "sans-serif" },
  { family: "Hanna",                 category: "display" },
  { family: "Inder",                 category: "sans-serif" },
  { family: "Istok Web",             category: "sans-serif" },
  { family: "Jaldi",                 category: "sans-serif" },
  { family: "Khand",                 category: "sans-serif" },
  { family: "Krub",                  category: "sans-serif" },
  { family: "Labrada",               category: "serif" },
  { family: "Laila",                 category: "serif" },
  { family: "Lateef",                category: "serif" },
  { family: "Lemonada",              category: "display" },
  { family: "Licorice",              category: "handwriting" },
  { family: "Linden Hill",           category: "serif" },
  { family: "Luxurious Roman",       category: "display" },
  { family: "Lynda",                 category: "sans-serif" },
  { family: "Macondo",               category: "display" },
  { family: "Magra",                 category: "sans-serif" },
  { family: "Martel",                category: "serif" },
  { family: "Martel Sans",           category: "sans-serif" },
  { family: "Mechanic",              category: "display" },
  { family: "Meera Inimai",          category: "sans-serif" },
  { family: "Metrophobic",           category: "sans-serif" },
  { family: "Michroma",              category: "sans-serif" },
  { family: "Mina",                  category: "sans-serif" },
  { family: "Miriam Libre",          category: "sans-serif" },
  { family: "Molengo",               category: "sans-serif" },
  { family: "Nobile",                category: "sans-serif" },
  { family: "Noticia Text",          category: "serif" },
  { family: "Nova Flat",             category: "display" },
  { family: "Nova Oval",             category: "display" },
  { family: "Nova Round",            category: "display" },
  { family: "Nova Script",           category: "display" },
  { family: "Nova Slim",             category: "display" },
  { family: "Oldenburg",             category: "display" },
  { family: "Oleo Script",           category: "display" },
  { family: "Ovo",                   category: "serif" },
  { family: "Podkova",               category: "serif" },
  { family: "Poly",                  category: "serif" },
  { family: "Prata",                 category: "serif" },
  { family: "Pridi",                 category: "serif" },
  { family: "Proza Libre",           category: "sans-serif" },
  { family: "Public Sans",           category: "sans-serif" },
  { family: "Puritan",               category: "sans-serif" },
  { family: "Questrial",             category: "sans-serif" },
  { family: "Rambla",                category: "sans-serif" },
  { family: "Rasa",                  category: "serif" },
  { family: "Rationale",             category: "sans-serif" },
  { family: "Rhodium Libre",         category: "serif" },
  { family: "Roboto Flex",           category: "sans-serif" },
  { family: "Ropa Sans",             category: "sans-serif" },
  { family: "Rosario",               category: "sans-serif" },
  { family: "Scada",                 category: "sans-serif" },
  { family: "Sen",                   category: "sans-serif" },
  { family: "Signika",               category: "sans-serif" },
  { family: "Signika Negative",      category: "sans-serif" },
  { family: "Simonetta",             category: "display" },
  { family: "Sintony",               category: "sans-serif" },
  { family: "Skranji",               category: "display" },
  { family: "Slabo 13px",            category: "serif" },
  { family: "Spartan",               category: "sans-serif" },
  { family: "Stardos Stencil",       category: "display" },
  { family: "Stint Ultra Condensed", category: "serif" },
  { family: "Strait",                category: "sans-serif" },
  { family: "Sunflower",             category: "sans-serif" },
  { family: "Supermercado One",      category: "display" },
  { family: "Suranna",               category: "serif" },
  { family: "Taviraj",               category: "serif" },
  { family: "Text Me One",           category: "sans-serif" },
  { family: "Thasadith",             category: "sans-serif" },
  { family: "The Girl Next Door",    category: "handwriting" },
  { family: "Tillana",               category: "handwriting" },
  { family: "Timmana",               category: "sans-serif" },
  { family: "Tinos",                 category: "serif" },
  { family: "Tourney",               category: "display" },
  { family: "Triforce",              category: "display" },
  { family: "Trirong",               category: "serif" },
  { family: "Trocchi",               category: "serif" },
  { family: "Trochut",               category: "display" },
  { family: "Trykker",               category: "serif" },
  { family: "Tulpen One",            category: "display" },
  { family: "Turret Road",           category: "display" },
  { family: "Ubuntu Condensed",      category: "sans-serif" },
  { family: "Unica One",             category: "display" },
  { family: "UnifrakturCook",        category: "display" },
  { family: "Unna",                  category: "serif" },
  { family: "Uchen",                 category: "serif" },
  { family: "Vast Shadow",           category: "display" },
  { family: "Vesper Libre",          category: "serif" },
  { family: "Vibes",                 category: "display" },
  { family: "Vidaloka",              category: "serif" },
  { family: "Viga",                  category: "sans-serif" },
  { family: "Voces",                 category: "sans-serif" },
  { family: "Volkhov",               category: "serif" },
  { family: "Voltaire",              category: "sans-serif" },
  { family: "Vujahday Script",       category: "handwriting" },
  { family: "Waiting for the Sunrise", category: "handwriting" },
  { family: "Wallpoet",              category: "display" },
  { family: "Walter Turncoat",       category: "handwriting" },
  { family: "Warnes",                category: "display" },
  { family: "Wellfleet",             category: "display" },
  { family: "Wendy One",             category: "sans-serif" },
  { family: "Wire One",              category: "sans-serif" },
  { family: "Xanh Mono",             category: "monospace" },
  { family: "Yaldevi",               category: "sans-serif" },
  { family: "Yanone Kaffeesatz",     category: "sans-serif" },
  { family: "Yantramanav",           category: "sans-serif" },
  { family: "Yatra One",             category: "display" },
  { family: "Yellowtail",            category: "handwriting" },
  { family: "Yeon Sung",             category: "display" },
  { family: "Yeseva One",            category: "display" },
  { family: "Yrsa",                  category: "serif" },
  { family: "Yuji Boku",             category: "serif" },
  { family: "Yuji Mai",              category: "serif" },
  { family: "Yuji Syuku",            category: "serif" },
  { family: "Yusei Magic",           category: "sans-serif" },
  { family: "ZCOOL KuaiLe",          category: "display" },
  { family: "ZCOOL QingKe HuangYou", category: "display" },
  { family: "ZCOOL XiaoWei",         category: "serif" },
  { family: "Zen Antique",           category: "serif" },
  { family: "Zen Kaku Gothic Antique", category: "sans-serif" },
  { family: "Zen Kaku Gothic New",   category: "sans-serif" },
  { family: "Zen Kurenaido",         category: "sans-serif" },
  { family: "Zen Loop",              category: "display" },
  { family: "Zen Maru Gothic",       category: "sans-serif" },
  { family: "Zen Old Mincho",        category: "serif" },
  { family: "Zilla Slab Highlight",  category: "display" },
];

/** Total count for display in the UI */
export const GOOGLE_FONTS_COUNT = GOOGLE_FONTS.length;

/** Category display labels */
export const CATEGORY_LABELS: Record<GoogleFontCategory, string> = {
  "sans-serif": "Sans Serif",
  "serif":      "Serif",
  "monospace":  "Monospace",
  "display":    "Display",
  "handwriting": "Handwriting",
};
