import { createThemeCustomizationOptions, defineTheme } from "@angee/ui/theme-runtime";

export const themes = [defineTheme({
  contractVersion: 1,
  id: "angee.fyltr",
  labelKey: "fyltr.label",
  descriptionKey: "fyltr.description",
  revision: 2,
  tokens: {
    shared: {
      "--font-family-sans": "Inter, SF Pro Display, system-ui, sans-serif",
      "--r-2": "4px",
      "--r-4": "6px",
      "--r-6": "8px",
      "--r-8": "10px",
      "--r-10": "12px",
      "--r-12": "12px",
      "--control-h-sm": "28px",
      "--control-h-md": "34px",
      "--control-h-lg": "40px",
    },
    light: {
      "--surface-canvas": "#f6faf8",
      "--surface-sheet": "#ffffff",
      "--surface-sheet-2": "#eef5f1",
      "--surface-rail": "#0b0f14",
      "--surface-rail-hi": "#1b262f",
      "--surface-popover": "#ffffff",
      "--surface-inset": "#e7f0eb",
      "--text-primary": "#0b0f14",
      "--text-secondary": "#26343d",
      "--text-muted": "#60717b",
      "--text-subtle": "#88969e",
      "--text-inverse": "#e6ecf1",
      "--text-on-rail": "#e6ecf1",
      "--text-on-rail-mut": "#92a1aa",
      "--text-on-rail-hi": "#ffffff",
      "--text-on-brand": "#0b0f14",
      "--text-link": "#007a34",
      "--border-subtle": "#dce7e1",
      "--border-default": "#c3d2ca",
      "--border-strong": "#91a59b",
      "--border-focus": "#00b84c",
      "--border-on-rail": "#1b262f",
      "--brand": "#00c853",
      "--brand-hover": "#00b84c",
      "--brand-active": "#009e42",
      "--brand-soft": "#daf8e5",
      "--brand-soft-text": "#007a34",
      "--accent": "#008f78",
      "--accent-soft": "#daf5ef",
      "--accent-soft-text": "#006b5a",
      "--success-soft": "#daf8e5",
      "--success-text": "#007a34",
      "--warning-soft": "#fff2cc",
      "--warning-text": "#805b00",
      "--danger-soft": "#ffe2e2",
      "--danger-text": "#b42318",
      "--info-soft": "#dceeff",
      "--info-text": "#175c9c",
      "--ring": "0 0 0 3px rgb(0 200 83 / 28%)",
      "--ring-danger": "0 0 0 3px rgb(220 38 38 / 30%)",
    },
    dark: {
      "--surface-canvas": "#0b0f14",
      "--surface-sheet": "#101820",
      "--surface-sheet-2": "#1b262f",
      "--surface-rail": "#070a0e",
      "--surface-rail-hi": "#1b262f",
      "--surface-popover": "#1b262f",
      "--surface-inset": "#131c24",
      "--text-primary": "#e6ecf1",
      "--text-secondary": "#c2cdd4",
      "--text-muted": "#92a1aa",
      "--text-subtle": "#65747e",
      "--text-inverse": "#0b0f14",
      "--text-on-rail": "#e6ecf1",
      "--text-on-rail-mut": "#92a1aa",
      "--text-on-rail-hi": "#ffffff",
      "--text-on-brand": "#0b0f14",
      "--text-link": "#45df7d",
      "--border-subtle": "#1b262f",
      "--border-default": "#32414c",
      "--border-strong": "#4b5b66",
      "--border-focus": "#00c853",
      "--border-on-rail": "#1b262f",
      "--brand": "#00c853",
      "--brand-hover": "#20dc6d",
      "--brand-active": "#53e98a",
      "--brand-soft": "#0c3220",
      "--brand-soft-text": "#5be98e",
      "--accent": "#29cbb0",
      "--accent-soft": "#103630",
      "--accent-soft-text": "#71e3cf",
      "--success-soft": "#0c3220",
      "--success-text": "#5be98e",
      "--warning-soft": "#382d12",
      "--warning-text": "#f6d365",
      "--danger-soft": "#401b1b",
      "--danger-text": "#ff9b9b",
      "--info-soft": "#142e43",
      "--info-text": "#86c9ff",
      "--ring": "0 0 0 3px rgb(0 200 83 / 35%)",
      "--ring-danger": "0 0 0 3px rgb(255 107 107 / 35%)",
    },
  },
  options: createThemeCustomizationOptions({
    brand: "#00c853",
    accent: "#008f78",
    neutral: "#60717b",
    font: "theme",
    radius: "theme",
    density: "theme",
    elevation: "theme",
  }),
})];
