# Generated by Django 6.0.6 on 2026-10-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def applies(state):
    """Only existing request schemas need the owner-owned account admission receipt."""
    need = state.models.get(("intake", "need"))
    return need is not None and "admitted_user" not in need.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='admitted_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
