# Generated by Django 6.0.6 on 2026-10-04 11:20

from django.db import migrations


def applies(state):
    """Retire the copied intake origin; the Need already points at its decision."""
    decision = state.models.get(("decisions", "decision"))
    return decision is not None and "intake_need" in decision.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '__latest__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='intake_need',
        ),
    ]
