# Generated by Django 6.0.6 on 2026-10-04 16:05

from django.db import migrations


def applies(state):
    """Discard old access questions and their applied account receipts with the owner cutover."""
    decision = state.models.get(("decisions", "decision"))
    need = state.models.get(("intake", "need"))
    return (
        decision is not None
        and {"form_schema", "step_run"}.intersection(decision.fields)
        and need is not None
        and {"access_decision", "admitted_user"}.issubset(need.fields)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("intake", "__latest__"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="need",
            name="access_decision",
        ),
        migrations.RemoveField(
            model_name="need",
            name="admitted_user",
        ),
    ]
