"""Operational work actions; resource reads remain generated by angee.mcp."""

from fastmcp import FastMCP

from angee.mcp.graphql import ACTION_RESULT, GraphQLTool, register_graphql_tools


def register(server: FastMCP) -> None:
    """Expose queue task verbs and cycle closure through their GraphQL owners."""

    register_graphql_tools(
        server,
        [
            GraphQLTool(
                operation="accept_task",
                name="accept_task",
                fields=ACTION_RESULT,
                id_arg="task",
                args=("stage", "expected_revision"),
                description="Accept a triage task into its selected or default stage.",
            ),
            GraphQLTool(
                operation="decline_task",
                name="decline_task",
                fields=ACTION_RESULT,
                id_arg="task",
                args=("reason", "expected_revision"),
                description="Decline a triage task for the selected reason.",
            ),
            GraphQLTool(
                operation="snooze_task",
                name="snooze_task",
                fields=ACTION_RESULT,
                id_arg="task",
                args=("until",),
                description="Snooze a triage task until the supplied time.",
            ),
            GraphQLTool(
                operation="mark_task_duplicate",
                name="mark_task_duplicate",
                fields=ACTION_RESULT,
                id_arg="task",
                args=("canonical",),
                description="Mark a task as a duplicate of another writable task.",
            ),
            GraphQLTool(
                operation="start_task",
                name="start_task",
                fields=ACTION_RESULT,
                id_arg="id",
                description="Start a writable queued task.",
            ),
            GraphQLTool(
                operation="return_task_to_triage",
                name="return_task_to_triage",
                fields=ACTION_RESULT,
                id_arg="id",
                description="Return a writable task to its queue's triage stage.",
            ),
            GraphQLTool(
                operation="remove_task",
                name="remove_task",
                fields=ACTION_RESULT,
                id_arg="task",
                args=("expected_revision",),
                description="Remove a task at its observed revision through its queue stage.",
            ),
            GraphQLTool(
                operation="close_work_cycle",
                name="close_work_cycle",
                fields=ACTION_RESULT,
                id_arg="cycle",
                description="Close a writable work cycle and roll unfinished tasks forward.",
            ),
            *(
                GraphQLTool(
                    operation=operation,
                    name=operation,
                    fields=ACTION_RESULT,
                    args=args,
                    description=description,
                )
                for operation, args, description in (
                    ("accept_tasks", ("selection",), "Accept selected tasks with their observed revisions."),
                    ("decline_tasks", ("selection", "reason"), "Decline selected tasks with their observed revisions."),
                    ("remove_tasks", ("selection",), "Remove selected tasks with their observed revisions."),
                )
            ),
        ],
    )
