# Generated by Django 6.0.6 on 2026-10-04 08:34

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


def applies(state):
    """Retire the complete old question schema; reject incomplete cutovers."""
    decision = state.models.get(("decisions", "decision"))
    if decision is None:
        return False
    legacy = {
        "subject_content_type", "subject_object_id", "closed_reason", "superseded_by",
        "supersede", "invalid_attempts", "max_attempts", "expires_at",
    }
    present = legacy.intersection(decision.fields)
    record = state.models.get(("decisions", "decisionrecord"))
    constraints = {item.name for item in decision.options.get("constraints", [])}
    indexes = {item.name for item in decision.options.get("indexes", [])}
    retired_constraints = {"decisions_open_subject_unique", "decisions_positive_attempts"}
    retired_indexes = {"decisions_open_expiry", "decisions_subject"}
    if not present:
        if "proposal" not in decision.fields or record is None or not {
            "decision", "content_type", "object_id",
        }.issubset(record.fields) or constraints & retired_constraints or indexes & retired_indexes:
            raise RuntimeError("The decisions record cutover is incomplete.")
        return False
    if present != legacy or "proposal" in decision.fields or record is not None or not (
        retired_constraints | {"decisions_resolution_consistent"}
    ).issubset(constraints) or not retired_indexes.issubset(indexes):
        raise RuntimeError("The legacy decisions schema is incomplete.")
    return True


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='decision',
            name='decisions_open_subject_unique',
        ),
        migrations.RemoveConstraint(
            model_name='decision',
            name='decisions_positive_attempts',
        ),
        migrations.RemoveConstraint(
            model_name='decision',
            name='decisions_resolution_consistent',
        ),
        migrations.RemoveIndex(
            model_name='decision',
            name='decisions_open_expiry',
        ),
        migrations.RemoveIndex(
            model_name='decision',
            name='decisions_subject',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='subject_content_type',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='subject_object_id',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='closed_reason',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='superseded_by',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='supersede',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='invalid_attempts',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='decision',
            name='proposal',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('verdict', 'pending')), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('verdict__in', ['completed', 'rejected', 'escalated'])), _connector='OR'), name='decisions_resolution_consistent'),
        ),
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('object_id', models.PositiveBigIntegerField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='decisions.decision')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_append_only_base',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='decisions_record_target')],
                'constraints': [models.UniqueConstraint(fields=('decision', 'content_type', 'object_id'), name='decisions_record_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_append_only_base', django.db.models.manager.Manager()),
            ],
        ),
    ]
