# Generated by Django 6.0.6 on 2026-10-04 16:05

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


def applies(state):
    """Discard old questions after their asking owners retire incoming links."""
    decision = state.models.get(("decisions", "decision"))
    if decision is None or "form_schema" not in decision.fields:
        return False
    legacy = {"form_schema", "basis", "errors", "group", "index", "resolution", "resolved_by", "resolved_at"}
    if not legacy.issubset(decision.fields):
        raise RuntimeError("The old decision schema is incomplete.")
    return not any(
        field.is_relation and field.remote_field.model.lower() in {"decisions.decision", "decisions.decisiongroup"}
        for (label, _), model in state.models.items()
        if label != "decisions"
        for field in model.fields.values()
        if isinstance(field.remote_field.model if field.is_relation else None, str)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "__latest__"),
        ("decisions", "__latest__"),
        ("iam", "__latest__"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DecisionRecord",
        ),
        migrations.DeleteModel(
            name="DecisionEvidence",
        ),
        migrations.DeleteModel(
            name="Decision",
        ),
        migrations.DeleteModel(
            name="DecisionGroup",
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("assignees", models.ManyToManyField(related_name="+", to=settings.AUTH_USER_MODEL)),
                ("context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=200)),
                ("proposal", models.JSONField()),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("verdict", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "_append_only_base",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("answered_at__isnull", True), ("answered_by__isnull", True), ("verdict__isnull", True)
                            ),
                            models.Q(
                                ("answered_at__isnull", False),
                                ("answered_by__isnull", False),
                                ("verdict__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="decisions_verdict_consistent",
                    )
                ],
                "default_manager_name": "objects",
                "indexes": [],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_append_only_base", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DecisionRecord",
            fields=[
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contenttypes.contenttype"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="records", to="decisions.decision"
                    ),
                ),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "_append_only_base",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("decision", "content_type", "object_id"), name="decisions_record_unique"
                    )
                ],
                "default_manager_name": "objects",
                "indexes": [models.Index(fields=["content_type", "object_id"], name="decisions_record_target")],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_append_only_base", django.db.models.manager.Manager()),
            ],
        ),
    ]
