# Generated by Django 6.0.6 on 2026-10-04 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def applies(state):
    """Wait for old waiter links to retire, then replace the complete question schema."""
    decision = state.models.get(("decisions", "decision"))
    if decision is None:
        return False
    legacy = {"form_schema", "basis", "errors", "group", "index", "resolution", "resolved_by", "resolved_at"}
    present = legacy.intersection(decision.fields)
    if not present:
        return False
    if present != legacy:
        raise RuntimeError("The old decision schema is incomplete.")
    step = state.models.get(("workflows", "steprun"))
    return step is None or "decision_group" not in step.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='decisionevidence',
            name='decisions_evidence_record',
        ),
        migrations.RemoveConstraint(
            model_name='decisionevidence',
            name='decisions_evidence_unique',
        ),
        migrations.RemoveField(
            model_name='decisiongroup',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='decisiongroup',
            name='reasked_from',
        ),
        migrations.RemoveConstraint(
            model_name='decision',
            name='decisions_group_index',
        ),
        migrations.RemoveConstraint(
            model_name='decision',
            name='decisions_resolution_consistent',
        ),
        migrations.AddField(
            model_name='decision',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decision',
            name='proposal',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='decision',
            name='verdict',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('answered_by__isnull', True), ('verdict__isnull', True)), models.Q(('answered_at__isnull', False), ('answered_by__isnull', False), ('verdict__isnull', False)), _connector='OR'), name='decisions_verdict_consistent'),
        ),
        migrations.RemoveField(
            model_name='decision',
            name='basis',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='form_schema',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='group',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='index',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='DecisionEvidence',
        ),
        migrations.DeleteModel(
            name='DecisionGroup',
        ),
    ]
